// Данные колоды: 49 карт. Лицо — картинка с цветом (assets/cards/front-XX.webp),
// рубашка — общий фон assets/back-bg.webp + логотип + фраза.
// Необязательные поля works / workLabels — фото готовых работ (5 дизайнов карты)
// и их подписи для галереи. Заполняются по мере готовности фото.
const CARDS = [
  { front: "assets/cards/front-01.webp",
    colors: ["Зелёные и бирюзовые","Оранжевые","Тёмные"],
    hexes: ["#0b7875","#ed691f","#1a2020","#c0e0c9","#f8bd95"],
    works: ["assets/works/card-01/1.webp","assets/works/card-01/2.webp","assets/works/card-01/3.webp","assets/works/card-01/4.webp","assets/works/card-01/5.webp"],
    workLabels: ["Глазурь-хром · однотон, глянец","Аура · френч (2 цв.)","Бархат cat-eye · однотон, матовый","Желе-стекло · омбре (2 цв.)","Жемчуг · однотон + блёстки"],
    phrase: "Твой маникюр – это способ выразить свой стиль, не произнося ни слова." },
  { front: "assets/cards/front-02.webp",
    colors: ["Розовые","Фиолетовые","Оранжевые","Синие","Жёлтые"],
    hexes: ["#cf1a81","#4d3185","#e5711c","#2b76ba","#f6df5b"],
    works: ["assets/works/card-02/1.webp","assets/works/card-02/2.webp","assets/works/card-02/3.webp","assets/works/card-02/4.webp","assets/works/card-02/5.webp"],
    workLabels: ["Голография · акцентный ноготь (2 цв.)","Матовый бархат · тон-в-тон микрофренч","Фольга · мрамор (3 цв.)","Дуохром · однотон + негатив-полоса","Матовое стекло · леопард-акцент (2 цв.)"],
    phrase: "Маникюр – это отражение личности." },
  { front: "assets/cards/front-03.webp",
    colors: ["Зелёные и бирюзовые","Красные","Синие"],
    hexes: ["#bedfe4","#712c1d","#4dbed0","#af282c","#253d7b"],
    works: ["assets/works/card-03/1.webp","assets/works/card-03/2.webp","assets/works/card-03/3.webp","assets/works/card-03/4.webp","assets/works/card-03/5.webp"],
    workLabels: ["Молочный · однотон + шиммер","Зеркальный хром · звёзды (2 цв.)","Сахар · матовый + глянцевая линия","Глазурь-хром · колор-блок (2 цв.)","Аура · однотон + аура"],
    phrase: "Идеальный маникюр – тот, с которым ты чувствуешь себя собой." },
  { front: "assets/cards/front-04.webp",
    colors: ["Жёлтые","Синие","Красные","Зелёные и бирюзовые"],
    hexes: ["#ffce08","#142b39","#034778","#e23c22","#0375ab"],
    works: ["assets/works/card-04/1.webp","assets/works/card-04/2.webp","assets/works/card-04/3.webp","assets/works/card-04/4.webp","assets/works/card-04/5.webp"],
    workLabels: ["Бархат cat-eye · абстракция (3 цв.)","Желе-стекло · однотон + хром-акцент","Жемчуг · волнистый френч (2 цв.)","Голография · однотон + глиттер-акцент","Матовый бархат · цветочки (3 цв.)"],
    phrase: "В дизайне ногтей границы устанавливает только твое воображение." },
  { front: "assets/cards/front-05.webp",
    colors: ["Светлые","Розовые","Зелёные и бирюзовые","Оранжевые","Синие"],
    hexes: ["#e5e7dc","#bb2183","#42bbc6","#f8b421","#2c53a0"],
    works: ["assets/works/card-05/1.webp","assets/works/card-05/2.webp","assets/works/card-05/3.webp","assets/works/card-05/4.webp","assets/works/card-05/5.webp"],
    workLabels: ["Фольга · однотон, глянец","Дуохром · френч (2 цв.)","Матовое стекло · однотон, матовый","Молочный · омбре (2 цв.)","Зеркальный хром · однотон + блёстки"],
    phrase: "Жизнь не может быть идеальной. А вот твои ногти – вполне." },
  { front: "assets/cards/front-06.webp",
    colors: ["Тёмные","Розовые","Зелёные и бирюзовые","Жёлтые","Оранжевые"],
    hexes: ["#201b21","#b21e74","#65c3cf","#dfc413","#f18b41"],
    works: ["assets/works/card-06/1.webp","assets/works/card-06/2.webp","assets/works/card-06/3.webp","assets/works/card-06/4.webp","assets/works/card-06/5.webp"],
    workLabels: ["Сахар · акцентный ноготь (2 цв.)","Глазурь-хром · тон-в-тон микрофренч","Аура · мрамор (3 цв.)","Бархат cat-eye · однотон + негатив-полоса","Желе-стекло · леопард-акцент (2 цв.)"],
    phrase: "Пусть день будет успешным, кофе крепким, а ногти – притягивающими взгляд." },
  { front: "assets/cards/front-07.webp",
    colors: ["Розовые","Фиолетовые","Жёлтые","Зелёные и бирюзовые"],
    hexes: ["#d0388b","#60214c","#483084","#fcc206","#56c3e4"],
    works: ["assets/works/card-07/1.webp","assets/works/card-07/2.webp","assets/works/card-07/3.webp","assets/works/card-07/4.webp","assets/works/card-07/5.webp"],
    workLabels: ["Жемчуг · однотон + шиммер","Голография · звёзды (2 цв.)","Матовый бархат · матовый + глянцевая линия","Фольга · колор-блок (2 цв.)","Дуохром · однотон + аура"],
    phrase: "Жизнь слишком коротка, чтобы не экспериментировать с маникюром!" },
  { front: "assets/cards/front-08.webp",
    colors: ["Синие","Зелёные и бирюзовые","Светлые","Розовые"],
    hexes: ["#8dc3e5","#9dd6e9","#e5d9e5","#76b5de","#c394c2"],
    works: ["assets/works/card-08/1.webp","assets/works/card-08/2.webp","assets/works/card-08/3.webp","assets/works/card-08/4.webp","assets/works/card-08/5.webp"],
    workLabels: ["Матовое стекло · абстракция (3 цв.)","Молочный · однотон + хром-акцент","Зеркальный хром · волнистый френч (2 цв.)","Сахар · однотон + глиттер-акцент","Глазурь-хром · цветочки (3 цв.)"],
    phrase: "Так много лаков, так мало ногтей!" },
  { front: "assets/cards/front-09.webp",
    colors: ["Светлые","Синие","Красные","Фиолетовые","Зелёные и бирюзовые"],
    hexes: ["#f1e5e9","#b7d5ed","#f39b8f","#bca2c9","#71c5e9"],
    works: ["assets/works/card-09/1.webp","assets/works/card-09/2.webp","assets/works/card-09/3.webp","assets/works/card-09/4.webp","assets/works/card-09/5.webp"],
    workLabels: ["Аура · однотон, глянец","Бархат cat-eye · френч (2 цв.)","Желе-стекло · однотон, матовый","Жемчуг · омбре (2 цв.)","Голография · однотон + блёстки"],
    phrase: "Женщина беспомощна только тогда, когда у нее сохнут ногти." },
  { front: "assets/cards/front-10.webp",
    colors: ["Синие","Розовые"],
    hexes: ["#d6d7e9","#b7c2de","#e6c4dd","#cba2cc","#8a96ca"],
    works: ["assets/works/card-10/1.webp","assets/works/card-10/2.webp","assets/works/card-10/3.webp","assets/works/card-10/4.webp","assets/works/card-10/5.webp"],
    workLabels: ["Матовый бархат · акцентный ноготь (2 цв.)","Фольга · тон-в-тон микрофренч","Дуохром · мрамор (3 цв.)","Матовое стекло · однотон + негатив-полоса","Молочный · леопард-акцент (2 цв.)"],
    phrase: "Красивый маникюр не изменит этот мир. А вот женщина с красивым маникюром на такое вполне способна." },
  { front: "assets/cards/front-11.webp",
    colors: ["Фиолетовые","Розовые","Светлые","Синие"],
    hexes: ["#9e7fb8","#e78eba","#e8e7ed","#b9c8e7","#f1d0e3"],
    works: ["assets/works/card-11/1.webp","assets/works/card-11/2.webp","assets/works/card-11/3.webp","assets/works/card-11/4.webp","assets/works/card-11/5.webp"],
    workLabels: ["Зеркальный хром · однотон + шиммер","Сахар · звёзды (2 цв.)","Глазурь-хром · матовый + глянцевая линия","Аура · колор-блок (2 цв.)","Бархат cat-eye · однотон + аура"],
    phrase: "Прелесть ногтей заключается в том, что их можно привести в форму без физических упражнений." },
  { front: "assets/cards/front-12.webp",
    colors: ["Зелёные и бирюзовые","Светлые","Нюд и бежевые"],
    hexes: ["#cbe1df","#e9dfe0","#66bfdd","#87ced4","#d2c6ae"],
    works: ["assets/works/card-12/1.webp","assets/works/card-12/2.webp","assets/works/card-12/3.webp","assets/works/card-12/4.webp","assets/works/card-12/5.webp"],
    workLabels: ["Ice-velvet cat-eye · Extra Celestial звёзды (2 цв.)","Желе (gummy) · кружево тон-в-тон (Laced Up)","Молочный · FunHaus полосы (2 цв.)","Матовый бархат · хром-кончики тон-в-тон","Опал/космос · микро-мотивы (3 цв.)"],
    phrase: "Маникюр – это вишенка на торте. Деталь необязательная, но как же она все меняет!" },
  { front: "assets/cards/front-13.webp",
    colors: ["Розовые","Синие","Светлые","Фиолетовые"],
    hexes: ["#dd9cc6","#b9c8e7","#f9f9fb","#a58dc1","#f0dce8"],
    works: ["assets/works/card-13/1.webp","assets/works/card-13/2.webp","assets/works/card-13/3.webp","assets/works/card-13/4.webp","assets/works/card-13/5.webp"],
    workLabels: ["Дуохром · плоский однотон","Фольга · френч (2 цв.)","Сахар · тон-в-тон микрофренч","Зеркальный хром · French ombré / baby boomer (2 цв.)","Матовое стекло · стеклянные 3D-точки"],
    phrase: "Творческую личность сразу видно по маникюру." },
  { front: "assets/cards/front-14.webp",
    colors: ["Зелёные и бирюзовые","Жёлтые"],
    hexes: ["#cde5d5","#fbf5ab","#d3b9d4","#91c9bc","#ced7d6"],
    works: ["assets/works/card-14/1.webp","assets/works/card-14/2.webp","assets/works/card-14/3.webp","assets/works/card-14/4.webp","assets/works/card-14/5.webp"],
    workLabels: ["Глянец · аура-блендинг (3 цв.)","Глазурь-хром · негатив-полоса","Жемчужный хром · Neo Deco шеврон (2 цв.)","Ice-velvet cat-eye · акцент другим финишем","Желе (gummy) · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Целеустремленность – это когда ты встаешь в свой единственный выходной в 7 утра, потому что у тебя запись на маникюр." },
  { front: "assets/cards/front-15.webp",
    colors: ["Красные","Оранжевые","Тёмные"],
    hexes: ["#e53424","#53201f","#eb5c22","#201b1f","#ea6321"],
    works: ["assets/works/card-15/1.webp","assets/works/card-15/2.webp","assets/works/card-15/3.webp","assets/works/card-15/4.webp","assets/works/card-15/5.webp"],
    workLabels: ["Молочный · Neo Deco веер (тон-в-тон)","Матовый бархат · Wilderkind анимал (2 цв.)","Опал/космос · аура тон-в-тон","Дуохром · мрамор (3 цв.)","Фольга · глиттер-акцент тон-в-тон"],
    phrase: "Красный маникюр – синоним уверенности и элегантности." },
  { front: "assets/cards/front-16.webp",
    colors: ["Красные","Оранжевые"],
    hexes: ["#83241e","#b02e21","#e84c23","#e6514b","#ca3224"],
    works: ["assets/works/card-16/1.webp","assets/works/card-16/2.webp","assets/works/card-16/3.webp","assets/works/card-16/4.webp","assets/works/card-16/5.webp"],
    workLabels: ["Сахар · Extra Celestial звёзды (2 цв.)","Зеркальный хром · кружево тон-в-тон (Laced Up)","Матовое стекло · FunHaus полосы (2 цв.)","Глянец · хром-кончики тон-в-тон","Глазурь-хром · микро-мотивы (3 цв.)"],
    phrase: "Находишься на перепутье? Ставь на красное!" },
  { front: "assets/cards/front-17.webp",
    colors: ["Красные","Зелёные и бирюзовые","Розовые"],
    hexes: ["#cc2127","#0b313e","#702047","#e6213c","#88222d"],
    works: ["assets/works/card-17/1.webp","assets/works/card-17/2.webp","assets/works/card-17/3.webp","assets/works/card-17/4.webp","assets/works/card-17/5.webp"],
    workLabels: ["Жемчужный хром · плоский однотон","Ice-velvet cat-eye · френч (2 цв.)","Желе (gummy) · тон-в-тон микрофренч","Молочный · French ombré / baby boomer (2 цв.)","Матовый бархат · стеклянные 3D-точки"],
    phrase: "Для каждой женщины найдется свой оттенок красного." },
  { front: "assets/cards/front-18.webp",
    colors: ["Розовые","Красные"],
    hexes: ["#e51859","#ae2422","#b11d57","#55224d","#e4202c"],
    works: ["assets/works/card-18/1.webp","assets/works/card-18/2.webp","assets/works/card-18/3.webp","assets/works/card-18/4.webp","assets/works/card-18/5.webp"],
    workLabels: ["Опал/космос · аура-блендинг (3 цв.)","Дуохром · негатив-полоса","Фольга · Neo Deco шеврон (2 цв.)","Сахар · акцент другим финишем","Зеркальный хром · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "С мастерами маникюра нужно поддерживать хорошие отношения. Они слишком много знают." },
  { front: "assets/cards/front-19.webp",
    colors: ["Красные","Тёмные"],
    hexes: ["#7f241f","#c9bbc8","#251b1c","#ab5c4f","#bf4961"],
    works: ["assets/works/card-19/1.webp","assets/works/card-19/2.webp","assets/works/card-19/3.webp","assets/works/card-19/4.webp","assets/works/card-19/5.webp"],
    workLabels: ["Матовое стекло · Neo Deco веер (тон-в-тон)","Глянец · Wilderkind анимал (2 цв.)","Глазурь-хром · аура тон-в-тон","Жемчужный хром · мрамор (3 цв.)","Ice-velvet cat-eye · глиттер-акцент тон-в-тон"],
    phrase: "Наша студия – это волшебное место, в котором рождается красота." },
  { front: "assets/cards/front-20.webp",
    colors: ["Красные","Розовые","Оранжевые"],
    hexes: ["#902421","#971f4c","#db3d24","#3a1e1d","#b8661d"],
    works: ["assets/works/card-20/1.webp","assets/works/card-20/2.webp","assets/works/card-20/3.webp","assets/works/card-20/4.webp","assets/works/card-20/5.webp"],
    workLabels: ["Желе (gummy) · Extra Celestial звёзды (2 цв.)","Молочный · кружево тон-в-тон (Laced Up)","Матовый бархат · FunHaus полосы (2 цв.)","Опал/космос · хром-кончики тон-в-тон","Дуохром · микро-мотивы (3 цв.)"],
    phrase: "Грустно, когда мастер показывает тебе 10 оттенков красного, но среди них нет того, который был бы достаточно красным для тебя." },
  { front: "assets/cards/front-21.webp",
    colors: ["Красные"],
    hexes: ["#942420","#c7c6cc","#423837","#ca3c28","#c36968"],
    works: ["assets/works/card-21/1.webp","assets/works/card-21/2.webp","assets/works/card-21/3.webp","assets/works/card-21/4.webp","assets/works/card-21/5.webp"],
    workLabels: ["Фольга · плоский однотон","Сахар · френч (2 цв.)","Зеркальный хром · тон-в-тон микрофренч","Матовое стекло · French ombré / baby boomer (2 цв.)","Глянец · стеклянные 3D-точки"],
    phrase: "Не стоит недооценивать силу хорошего маникюра." },
  { front: "assets/cards/front-22.webp",
    colors: ["Красные","Розовые","Светлые"],
    hexes: ["#c92130","#e51468","#fdf8f8","#f9ccc6","#a62424"],
    works: ["assets/works/card-22/1.webp","assets/works/card-22/2.webp","assets/works/card-22/3.webp","assets/works/card-22/4.webp","assets/works/card-22/5.webp"],
    workLabels: ["Глазурь-хром · аура-блендинг (3 цв.)","Жемчужный хром · негатив-полоса","Ice-velvet cat-eye · Neo Deco шеврон (2 цв.)","Желе (gummy) · акцент другим финишем","Молочный · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Ничто не поднимает настроение так, как свежий маникюр." },
  { front: "assets/cards/front-23.webp",
    colors: ["Красные","Светлые","Розовые"],
    hexes: ["#e51e47","#efe4f2","#e53623","#f1bbd5","#ea587c"],
    works: ["assets/works/card-23/1.webp","assets/works/card-23/2.webp","assets/works/card-23/3.webp","assets/works/card-23/4.webp","assets/works/card-23/5.webp"],
    workLabels: ["Матовый бархат · Neo Deco веер (тон-в-тон)","Опал/космос · Wilderkind анимал (2 цв.)","Дуохром · аура тон-в-тон","Фольга · мрамор (3 цв.)","Сахар · глиттер-акцент тон-в-тон"],
    phrase: "Маникюр без дизайна – как небо без звезд." },
  { front: "assets/cards/front-24.webp",
    colors: ["Розовые","Красные","Светлые"],
    hexes: ["#e786a9","#d32024","#e74554","#ed929b","#efe1f0"],
    works: ["assets/works/card-24/1.webp","assets/works/card-24/2.webp","assets/works/card-24/3.webp","assets/works/card-24/4.webp","assets/works/card-24/5.webp"],
    workLabels: ["Зеркальный хром · Extra Celestial звёзды (2 цв.)","Матовое стекло · кружево тон-в-тон (Laced Up)","Глянец · FunHaus полосы (2 цв.)","Глазурь-хром · хром-кончики тон-в-тон","Жемчужный хром · микро-мотивы (3 цв.)"],
    phrase: "Зачем смотреть на негатив вокруг, если можно любоваться свежесделанными ноготочками?" },
  { front: "assets/cards/front-25.webp",
    colors: ["Красные","Оранжевые","Розовые","Светлые","Зелёные и бирюзовые"],
    hexes: ["#ebccd2","#ee7c3d","#df5a9b","#dfdfe9","#548d9e"],
    works: ["assets/works/card-25/1.webp","assets/works/card-25/2.webp","assets/works/card-25/3.webp","assets/works/card-25/4.webp","assets/works/card-25/5.webp"],
    workLabels: ["Ice-velvet cat-eye · плоский однотон","Желе (gummy) · френч (2 цв.)","Молочный · тон-в-тон микрофренч","Матовый бархат · French ombré / baby boomer (2 цв.)","Опал/космос · стеклянные 3D-точки"],
    phrase: "Который сейчас час? Самое время записаться к мастеру и сотворить на своих ногтях очередной шедевр!" },
  { front: "assets/cards/front-26.webp",
    colors: ["Светлые","Розовые","Красные"],
    hexes: ["#f9dad5","#d5157c","#fdfdfd","#f6b5b9","#f297a8"],
    works: ["assets/works/card-26/1.webp","assets/works/card-26/2.webp","assets/works/card-26/3.webp","assets/works/card-26/4.webp","assets/works/card-26/5.webp"],
    workLabels: ["Дуохром · аура-блендинг (3 цв.)","Фольга · негатив-полоса","Сахар · Neo Deco шеврон (2 цв.)","Зеркальный хром · акцент другим финишем","Матовое стекло · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Минимализм – это здорово, но без глиттера жизнь была бы куда скучнее." },
  { front: "assets/cards/front-27.webp",
    colors: ["Красные","Светлые","Оранжевые"],
    hexes: ["#f3a6b8","#ce3956","#fbe5e7","#a0a8b5","#dbb76b"],
    works: ["assets/works/card-27/1.webp","assets/works/card-27/2.webp","assets/works/card-27/3.webp","assets/works/card-27/4.webp","assets/works/card-27/5.webp"],
    workLabels: ["Глянец · Neo Deco веер (тон-в-тон)","Глазурь-хром · Wilderkind анимал (2 цв.)","Жемчужный хром · аура тон-в-тон","Ice-velvet cat-eye · мрамор (3 цв.)","Желе (gummy) · глиттер-акцент тон-в-тон"],
    phrase: "Добавь в свою жизнь ярких красок – сделай новый маникюр!" },
  { front: "assets/cards/front-28.webp",
    colors: ["Розовые","Красные","Светлые"],
    hexes: ["#eb5a9b","#632122","#838d96","#dbe6e0","#f7c5d1"],
    works: ["assets/works/card-28/1.webp","assets/works/card-28/2.webp","assets/works/card-28/3.webp","assets/works/card-28/4.webp","assets/works/card-28/5.webp"],
    workLabels: ["Молочный · Extra Celestial звёзды (2 цв.)","Матовый бархат · кружево тон-в-тон (Laced Up)","Опал/космос · FunHaus полосы (2 цв.)","Дуохром · хром-кончики тон-в-тон","Фольга · микро-мотивы (3 цв.)"],
    phrase: "Ничто так не греет душу, как мысль о том, что ты успела записаться к любимому мастеру." },
  { front: "assets/cards/front-29.webp",
    colors: ["Синие","Зелёные и бирюзовые"],
    hexes: ["#5ba5d2","#104d90","#d8edf0","#292f61","#20253b"],
    works: ["assets/works/card-29/1.webp","assets/works/card-29/2.webp","assets/works/card-29/3.webp","assets/works/card-29/4.webp","assets/works/card-29/5.webp"],
    workLabels: ["Сахар · плоский однотон","Зеркальный хром · френч (2 цв.)","Матовое стекло · тон-в-тон микрофренч","Глянец · French ombré / baby boomer (2 цв.)","Глазурь-хром · стеклянные 3D-точки"],
    phrase: "Длинные ногти созданы для того, чтобы драматично набирать сообщения на телефоне." },
  { front: "assets/cards/front-30.webp",
    colors: ["Зелёные и бирюзовые","Фиолетовые","Синие","Светлые"],
    hexes: ["#cbe7ea","#493185","#8696ca","#9ec6e9","#f4faf8"],
    works: ["assets/works/card-30/1.webp","assets/works/card-30/2.webp","assets/works/card-30/3.webp","assets/works/card-30/4.webp","assets/works/card-30/5.webp"],
    workLabels: ["Жемчужный хром · аура-блендинг (3 цв.)","Ice-velvet cat-eye · негатив-полоса","Желе (gummy) · Neo Deco шеврон (2 цв.)","Молочный · акцент другим финишем","Матовый бархат · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Прогулка до маникюрного салона – это тоже своего рода тренировка." },
  { front: "assets/cards/front-31.webp",
    colors: ["Светлые","Фиолетовые","Синие","Зелёные и бирюзовые"],
    hexes: ["#e3f0e9","#292139","#302f6b","#5ca8ca","#19659f"],
    works: ["assets/works/card-31/1.webp","assets/works/card-31/2.webp","assets/works/card-31/3.webp","assets/works/card-31/4.webp","assets/works/card-31/5.webp"],
    workLabels: ["Опал/космос · Neo Deco веер (тон-в-тон)","Дуохром · Wilderkind анимал (2 цв.)","Фольга · аура тон-в-тон","Сахар · мрамор (3 цв.)","Зеркальный хром · глиттер-акцент тон-в-тон"],
    phrase: "Твой маникюр может сказать о тебе больше, чем ты сама." },
  { front: "assets/cards/front-32.webp",
    colors: ["Синие","Светлые","Зелёные и бирюзовые"],
    hexes: ["#1e3a6a","#f7f7ef","#26233e","#12b1b7","#04627e"],
    works: ["assets/works/card-32/1.webp","assets/works/card-32/2.webp","assets/works/card-32/3.webp","assets/works/card-32/4.webp","assets/works/card-32/5.webp"],
    workLabels: ["Матовое стекло · Extra Celestial звёзды (2 цв.)","Глянец · кружево тон-в-тон (Laced Up)","Глазурь-хром · FunHaus полосы (2 цв.)","Жемчужный хром · хром-кончики тон-в-тон","Ice-velvet cat-eye · микро-мотивы (3 цв.)"],
    phrase: "Диснейленд? Пф! Настоящее волшебство творится здесь!" },
  { front: "assets/cards/front-33.webp",
    colors: ["Зелёные и бирюзовые","Нюд и бежевые"],
    hexes: ["#cbe7e8","#95d1d9","#147183","#014962","#c9c3a3"],
    works: ["assets/works/card-33/1.webp","assets/works/card-33/2.webp","assets/works/card-33/3.webp","assets/works/card-33/4.webp","assets/works/card-33/5.webp"],
    workLabels: ["Желе (gummy) · плоский однотон","Молочный · френч (2 цв.)","Матовый бархат · тон-в-тон микрофренч","Опал/космос · French ombré / baby boomer (2 цв.)","Дуохром · стеклянные 3D-точки"],
    phrase: "Каким бы плохим ни был твой день, главное, чтобы у тебя был хороший маникюр." },
  { front: "assets/cards/front-34.webp",
    colors: ["Зелёные и бирюзовые","Синие","Светлые"],
    hexes: ["#31aee4","#b2cdeb","#5172b5","#e8f5fd","#3a3f90"],
    works: ["assets/works/card-34/1.webp","assets/works/card-34/2.webp","assets/works/card-34/3.webp","assets/works/card-34/4.webp","assets/works/card-34/5.webp"],
    workLabels: ["Фольга · аура-блендинг (3 цв.)","Сахар · негатив-полоса","Зеркальный хром · Neo Deco шеврон (2 цв.)","Матовое стекло · акцент другим финишем","Глянец · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Заботы заботами, а на маникюр записаться не забудь." },
  { front: "assets/cards/front-35.webp",
    colors: ["Зелёные и бирюзовые","Синие","Тёмные"],
    hexes: ["#3cbcd7","#38317e","#c2d1d8","#232033","#195fa5"],
    works: ["assets/works/card-35/1.webp","assets/works/card-35/2.webp","assets/works/card-35/3.webp","assets/works/card-35/4.webp","assets/works/card-35/5.webp"],
    workLabels: ["Глазурь-хром · Neo Deco веер (тон-в-тон)","Жемчужный хром · Wilderkind анимал (2 цв.)","Ice-velvet cat-eye · аура тон-в-тон","Желе (gummy) · мрамор (3 цв.)","Молочный · глиттер-акцент тон-в-тон"],
    phrase: "Окружай себя красотой, а не негативом." },
  { front: "assets/cards/front-36.webp",
    colors: ["Светлые","Оранжевые","Нюд и бежевые"],
    hexes: ["#f9f9f8","#a67044","#696969","#f6c88a","#c8b99c"],
    works: ["assets/works/card-36/1.webp","assets/works/card-36/2.webp","assets/works/card-36/3.webp","assets/works/card-36/4.webp","assets/works/card-36/5.webp"],
    workLabels: ["Матовый бархат · Extra Celestial звёзды (2 цв.)","Опал/космос · кружево тон-в-тон (Laced Up)","Дуохром · FunHaus полосы (2 цв.)","Фольга · хром-кончики тон-в-тон","Сахар · микро-мотивы (3 цв.)"],
    phrase: "Лак без блесток – как торт без глазури." },
  { front: "assets/cards/front-37.webp",
    colors: ["Жёлтые","Нюд и бежевые","Светлые","Оранжевые"],
    hexes: ["#b0851d","#b2b4af","#b58b59","#e6ebee","#533f26"],
    works: ["assets/works/card-37/1.webp","assets/works/card-37/2.webp","assets/works/card-37/3.webp","assets/works/card-37/4.webp","assets/works/card-37/5.webp"],
    workLabels: ["Зеркальный хром · плоский однотон","Матовое стекло · френч (2 цв.)","Глянец · тон-в-тон микрофренч","Глазурь-хром · French ombré / baby boomer (2 цв.)","Жемчужный хром · стеклянные 3D-точки"],
    phrase: "Если он не похвалил твой новый маникюр, то он не стоит твоих слез, дорогая!" },
  { front: "assets/cards/front-38.webp",
    colors: ["Светлые","Жёлтые","Нюд и бежевые","Синие"],
    hexes: ["#dce4e6","#e4c46d","#f1e9dc","#c0d6e3","#b79d2e"],
    works: ["assets/works/card-38/1.webp","assets/works/card-38/2.webp","assets/works/card-38/3.webp","assets/works/card-38/4.webp","assets/works/card-38/5.webp"],
    workLabels: ["Ice-velvet cat-eye · аура-блендинг (3 цв.)","Желе (gummy) · негатив-полоса","Молочный · Neo Deco шеврон (2 цв.)","Матовый бархат · акцент другим финишем","Опал/космос · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Понедельник легче пережить, когда ты знаешь, что вечером у тебя запись к любимому мастеру." },
  { front: "assets/cards/front-39.webp",
    colors: ["Оранжевые","Жёлтые","Тёмные"],
    hexes: ["#c4892d","#7d5329","#9e9c9f","#eacd69","#332c26"],
    works: ["assets/works/card-39/1.webp","assets/works/card-39/2.webp","assets/works/card-39/3.webp","assets/works/card-39/4.webp","assets/works/card-39/5.webp"],
    workLabels: ["Дуохром · Neo Deco веер (тон-в-тон)","Фольга · Wilderkind анимал (2 цв.)","Сахар · аура тон-в-тон","Зеркальный хром · мрамор (3 цв.)","Матовое стекло · глиттер-акцент тон-в-тон"],
    phrase: "Захотелось перемен? Начни с маникюра!" },
  { front: "assets/cards/front-40.webp",
    colors: ["Оранжевые","Нюд и бежевые"],
    hexes: ["#bcb8b7","#7d512a","#fbfaf6","#81807e","#bf9660"],
    works: ["assets/works/card-40/1.webp","assets/works/card-40/2.webp","assets/works/card-40/3.webp","assets/works/card-40/4.webp","assets/works/card-40/5.webp"],
    workLabels: ["Глянец · Extra Celestial звёзды (2 цв.)","Глазурь-хром · кружево тон-в-тон (Laced Up)","Жемчужный хром · FunHaus полосы (2 цв.)","Ice-velvet cat-eye · хром-кончики тон-в-тон","Желе (gummy) · микро-мотивы (3 цв.)"],
    phrase: "Жизнь коротка, поэтому ногти должны быть длинными." },
  { front: "assets/cards/front-41.webp",
    colors: ["Нюд и бежевые","Синие"],
    hexes: ["#c6ac6f","#cbb59d","#415d72","#686868","#1d2b34"],
    works: ["assets/works/card-41/1.webp","assets/works/card-41/2.webp","assets/works/card-41/3.webp","assets/works/card-41/4.webp","assets/works/card-41/5.webp"],
    workLabels: ["Молочный · плоский однотон","Матовый бархат · френч (2 цв.)","Опал/космос · тон-в-тон микрофренч","Дуохром · French ombré / baby boomer (2 цв.)","Фольга · стеклянные 3D-точки"],
    phrase: "Поход на маникюр – это тоже терапия." },
  { front: "assets/cards/front-42.webp",
    colors: ["Нюд и бежевые","Оранжевые"],
    hexes: ["#dfd6cf","#d8a963","#a26b44","#52555c","#3d2d1d"],
    works: ["assets/works/card-42/1.webp","assets/works/card-42/2.webp","assets/works/card-42/3.webp","assets/works/card-42/4.webp","assets/works/card-42/5.webp"],
    workLabels: ["Сахар · аура-блендинг (3 цв.)","Зеркальный хром · негатив-полоса","Матовое стекло · Neo Deco шеврон (2 цв.)","Глянец · акцент другим финишем","Глазурь-хром · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Ничто так не бодрит с утра, как осознание того, что ты опаздываешь на маникюр." },
  { front: "assets/cards/front-43.webp",
    colors: ["Тёмные","Светлые"],
    hexes: ["#201b21","#cdcdcd","#fcfcfc","#848484","#535353"],
    works: ["assets/works/card-43/1.webp","assets/works/card-43/2.webp","assets/works/card-43/3.webp","assets/works/card-43/4.webp","assets/works/card-43/5.webp"],
    workLabels: ["Жемчужный хром · Neo Deco веер (тон-в-тон)","Ice-velvet cat-eye · Wilderkind анимал (2 цв.)","Желе (gummy) · аура тон-в-тон","Молочный · мрамор (3 цв.)","Матовый бархат · глиттер-акцент тон-в-тон"],
    phrase: "Отличный день – это когда твоей единственной заботой является выбор дизайна для очередного маникюра." },
  { front: "assets/cards/front-44.webp",
    colors: ["Тёмные","Зелёные и бирюзовые"],
    hexes: ["#1e1e20","#b6bac3","#0995a2","#585453","#6e797b"],
    works: ["assets/works/card-44/1.webp","assets/works/card-44/2.webp","assets/works/card-44/3.webp","assets/works/card-44/4.webp","assets/works/card-44/5.webp"],
    workLabels: ["Опал/космос · Extra Celestial звёзды (2 цв.)","Дуохром · кружево тон-в-тон (Laced Up)","Фольга · FunHaus полосы (2 цв.)","Сахар · хром-кончики тон-в-тон","Зеркальный хром · микро-мотивы (3 цв.)"],
    phrase: "Если после выхода из салона тебе не хочется любоваться ноготочками 24/7, значит, пора сменить мастера." },
  { front: "assets/cards/front-45.webp",
    colors: ["Тёмные","Светлые"],
    hexes: ["#1e1c1f","#6b6b6b","#b0b2b1","#e7e7e7","#494949"],
    works: ["assets/works/card-45/1.webp","assets/works/card-45/2.webp","assets/works/card-45/3.webp","assets/works/card-45/4.webp","assets/works/card-45/5.webp"],
    workLabels: ["Матовое стекло · плоский однотон","Глянец · френч (2 цв.)","Глазурь-хром · тон-в-тон микрофренч","Жемчужный хром · French ombré / baby boomer (2 цв.)","Ice-velvet cat-eye · стеклянные 3D-точки"],
    phrase: "Нет человека более целеустремленного, чем девушка, которой нужно успеть сделать маникюр перед важным событием." },
  { front: "assets/cards/front-46.webp",
    colors: ["Светлые","Тёмные"],
    hexes: ["#fbfcf7","#686a76","#494c55","#abaaaf","#212530"],
    works: ["assets/works/card-46/1.webp","assets/works/card-46/2.webp","assets/works/card-46/3.webp","assets/works/card-46/4.webp","assets/works/card-46/5.webp"],
    workLabels: ["Желе (gummy) · аура-блендинг (3 цв.)","Молочный · негатив-полоса","Матовый бархат · Neo Deco шеврон (2 цв.)","Опал/космос · акцент другим финишем","Дуохром · кружево-акцент (Laced Up, 2 цв.)"],
    phrase: "Мастера маникюра – вот кто делает нашу с вами жизнь чуточку ярче и прекраснее." },
  { front: "assets/cards/front-47.webp",
    colors: ["Тёмные","Светлые"],
    hexes: ["#858585","#2f2f2f","#f1f1f1","#616161","#dddddd"],
    works: ["assets/works/card-47/1.webp","assets/works/card-47/2.webp","assets/works/card-47/3.webp","assets/works/card-47/4.webp","assets/works/card-47/5.webp"],
    workLabels: ["Фольга · Neo Deco веер (тон-в-тон)","Сахар · Wilderkind анимал (2 цв.)","Зеркальный хром · аура тон-в-тон","Матовое стекло · мрамор (3 цв.)","Глянец · глиттер-акцент тон-в-тон"],
    phrase: "Дела делами, а коррекция по расписанию." },
  { front: "assets/cards/front-48.webp",
    colors: ["Тёмные","Светлые","Жёлтые"],
    hexes: ["#1e1e1e","#fcf5ed","#e6e6e6","#cfa012","#b0b0ae"],
    works: ["assets/works/card-48/1.webp","assets/works/card-48/2.webp","assets/works/card-48/3.webp","assets/works/card-48/4.webp","assets/works/card-48/5.webp"],
    workLabels: ["Глазурь-хром · Extra Celestial звёзды (2 цв.)","Жемчужный хром · кружево тон-в-тон (Laced Up)","Ice-velvet cat-eye · FunHaus полосы (2 цв.)","Желе (gummy) · хром-кончики тон-в-тон","Молочный · микро-мотивы (3 цв.)"],
    phrase: "Неловкий момент – это когда ты приходишь к своему мастеру, а на твоих ногтях чужое покрытие..." },
  { front: "assets/cards/front-49.webp",
    colors: ["Тёмные","Оранжевые"],
    hexes: ["#1f1f21","#6c6c6e","#cecfca","#e1b878","#454a50"],
    works: ["assets/works/card-49/1.webp","assets/works/card-49/2.webp","assets/works/card-49/3.webp","assets/works/card-49/4.webp","assets/works/card-49/5.webp"],
    workLabels: ["Матовый бархат · плоский однотон","Опал/космос · френч (2 цв.)","Дуохром · тон-в-тон микрофренч","Фольга · French ombré / baby boomer (2 цв.)","Сахар · стеклянные 3D-точки"],
    phrase: "А поход на маникюр раз в три недели считается за хобби?" },
];
